"use client";

import { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence, Variants } from 'framer-motion'; // FIX: Ambil interface Variants dari sini
import Lenis from '@studio-freight/lenis';
import styles from './projects.module.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';

import PROJECTS_DATA from '@/json/projects.json';

interface ProjectItem {
  id: number;
  title: string;
  description: string;
  tags: string[];
  github: string;
}

export default function ProjectsPage() {
  const [activeTag, setActiveTag] = useState<string>("All");
  const [isOverflowing, setIsOverflowing] = useState<boolean>(false);
  
  const containerRef = useRef<HTMLDivElement>(null);
  const trackRef = useRef<HTMLDivElement>(null);

  // Arsitektur Physics Engine State
  const pointerState = useRef({
    isDown: false,
    startX: 0,
    currentX: 0,
    lastX: 0,
    velocityX: 0,
    targetX: 0, // Koordinat posisi virtual rel
    singleSetWidth: 0,
  });

  const isDraggingRef = useRef<boolean>(false);

  // 1. Logic Smooth Scroll Lenis untuk Halaman Utama
  useEffect(() => {
    const lenis = new Lenis({
      duration: 1.2,
      easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
      smoothWheel: true,
    });

    function raf(time: number) {
      lenis.raf(time);
      requestAnimationFrame(raf);
    }

    requestAnimationFrame(raf);
    return () => lenis.destroy();
  }, []);

  const projectsList = useMemo<ProjectItem[]>(() => {
    return Array.isArray(PROJECTS_DATA) ? PROJECTS_DATA : PROJECTS_DATA.projects;
  }, []);

  const filteredProjects = useMemo<ProjectItem[]>(() => {
    return activeTag === "All" 
      ? projectsList 
      : projectsList.filter((project) => project.tags.includes(activeTag));
  }, [activeTag, projectsList]);

  const autoGeneratedTags = useMemo<string[]>(() => {
    const tagsSet = new Set<string>();
    projectsList.forEach((project) => {
      if (project.tags && Array.isArray(project.tags)) {
        project.tags.forEach((tag) => tagsSet.add(tag));
      }
    });
    return ["All", ...Array.from(tagsSet)];
  }, [projectsList]);

  const renderedTags = useMemo(() => {
    return isOverflowing 
      ? [...autoGeneratedTags, ...autoGeneratedTags, ...autoGeneratedTags] 
      : autoGeneratedTags;
  }, [autoGeneratedTags, isOverflowing]);

  // 2. Deteksi Ukuran Riil & Set Posisi Awal Track Kereta
  useEffect(() => {
    const container = containerRef.current;
    const track = trackRef.current;
    if (!container || !track) return;

    const calculateSizes = () => {
      const containerWidth = container.clientWidth;
      const trackWidth = track.scrollWidth;

      if (!isOverflowing) {
        if (trackWidth > containerWidth) {
          setIsOverflowing(true);
        }
      } else {
        const singleSet = trackWidth / 3;
        pointerState.current.singleSetWidth = singleSet;
        
        if (singleSet <= containerWidth) {
          setIsOverflowing(false);
          pointerState.current.targetX = 0;
          track.style.transform = `translate3d(0px, 0px, 0px)`;
        } else {
          // Posisikan kereta tepat di awal klaster ke-2 (tengah-tengah)
          pointerState.current.targetX = -singleSet;
        }
      }
    };

    const timeoutId = setTimeout(calculateSizes, 60);
    window.addEventListener('resize', calculateSizes);

    return () => {
      clearTimeout(timeoutId);
      window.removeEventListener('resize', calculateSizes);
    };
  }, [autoGeneratedTags, isOverflowing]);

  // 3. VIRTUAL PHYSICS MOMENTUM ENGINE (The Rail Loop System)
  useEffect(() => {
    const track = trackRef.current;
    if (!track || !isOverflowing) return;

    let animationFrameId: number;
    const state = pointerState.current;

    const updatePhysics = () => {
      // Jika jari lepas, aplikasikan gaya gesek peluruhan (Decay Multiplier: 0.95)
      if (!state.isDown) {
        state.targetX += state.velocityX;
        state.velocityX *= 0.95; // Semakin kecil angka, rem semakin pakem
        
        // Hentikan micro-movement jika kecepatan sudah mendekati nol
        if (Math.abs(state.velocityX) < 0.1) state.velocityX = 0;
      } else {
        // Akumulasi kalkulasi kecepatan instan berdasarkan pergeseran frame delta X
        state.velocityX = state.currentX - state.lastX;
        state.lastX = state.currentX;
      }

      // SEAMLESS LOOP RE-CENTERING LOGIC (Batasan Gerak Kereta)
      const singleSet = state.singleSetWidth;
      
      // Klaster 3 Terlampaui (Geser Kiri ekstrem) -> Snap Balik ke Klaster 2
      if (state.targetX <= -(singleSet * 2)) {
        state.targetX += singleSet;
      }
      // Klaster 1 Terlampaui (Geser Kanan ekstrem) -> Snap Balik ke Klaster 2
      else if (state.targetX >= 0) {
        state.targetX -= singleSet;
      }

      // Update posisi fisik DOM menggunakan Hardware-Accelerated 3D Transform
      track.style.transform = `translate3d(${state.targetX}px, 0px, 0px)`;

      animationFrameId = requestAnimationFrame(updatePhysics);
    };

    animationFrameId = requestAnimationFrame(updatePhysics);
    return () => cancelAnimationFrame(animationFrameId);
  }, [isOverflowing, renderedTags]);

  // 4. UNIFIED GESTURE EVENT HANDLERS (MOUSE & TOUCH INTEGRATION)
  const pointerDown = (clientX: number) => {
    const state = pointerState.current;
    state.isDown = true;
    isDraggingRef.current = false;
    state.startX = clientX - state.targetX;
    state.currentX = clientX;
    state.lastX = clientX;
    state.velocityX = 0;
    
    if (trackRef.current) {
      trackRef.current.style.cursor = 'grabbing';
    }
  };

  const pointerMove = (clientX: number) => {
    const state = pointerState.current;
    if (!state.isDown) return;

    state.currentX = clientX;
    const newTargetX = clientX - state.startX;

    if (Math.abs(newTargetX - state.targetX) > 4) {
      isDraggingRef.current = true;
    }

    state.targetX = newTargetX;
  };

  const pointerUp = () => {
    const state = pointerState.current;
    state.isDown = false;
    
    if (trackRef.current) {
      trackRef.current.style.cursor = 'grab';
    }
    
    // Proteksi klik tombol pasca menyeret rel
    setTimeout(() => {
      isDraggingRef.current = false;
    }, 20);
  };

  const handleTagClick = (tag: string) => {
    if (isDraggingRef.current) return;
    setActiveTag(activeTag === tag ? "All" : tag);
  };

  // FIX: Menambahkan tipe ekplisit ': Variants' agar fungsi custom dinamis & properti tipe spring divalidasi dengan aman
  const blockStackVariants: Variants = {
    hidden: { opacity: 0, x: 100, y: -50, rotateZ: 5, rotateY: -10, scale: 1.05 },
    visible: (customIndex: number) => ({ 
      opacity: 1, x: 0, y: 0, rotateZ: 0, rotateY: 0, scale: 1,
      transition: { type: "spring", stiffness: 85, damping: 14, mass: 0.8, delay: customIndex * 0.06 }
    })
  };

  return (
    <div className={styles.container}>
      <Navbar />

      <main className={styles.main}>
        {/* Hero Section */}
        <section className={styles.hero}>
          <motion.h1 
            className={styles.heroTitle}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            PROJECTS
          </motion.h1>
          <motion.p 
            className={styles.heroSub}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8 }}
          >
            A curated repository of systems, models, and technical explorations.
          </motion.p>
        </section>

        {/* Filter Bar Section (The Rail Constraints Viewport) */}
        <div 
          ref={containerRef}
          className={`${styles.filterBarWrapper} ${isOverflowing ? styles.hasMask : ''}`}
          onTouchStart={(e) => pointerDown(e.touches[0].clientX)}
          onTouchMove={(e) => pointerMove(e.touches[0].clientX)}
          onTouchEnd={pointerUp}
          onMouseDown={(e) => pointerDown(e.clientX)}
          onMouseMove={(e) => { e.preventDefault(); pointerMove(e.clientX); }}
          onMouseUp={pointerUp}
          onMouseLeave={pointerUp}
        >
          <div 
            ref={trackRef}
            className={`${styles.filterBar} ${isOverflowing ? styles.canScroll : styles.isCentered}`}
          >
            {renderedTags.map((tag, index) => (
              <button 
                key={`${tag}-${index}`}
                onClick={() => handleTagClick(tag)}
                className={`${styles.filterBtn} ${activeTag === tag ? styles.active : ''}`}
              >
                {tag}
              </button>
            ))}
          </div>
        </div>

        {/* Projects List Container */}
        <section className={styles.listContainer}>
          <AnimatePresence mode="popLayout">
            {filteredProjects.map((project, index) => (
              <motion.div 
                key={project.id}
                layout 
                custom={index}
                variants={blockStackVariants}
                initial="hidden"
                whileInView="visible" 
                viewport={{ once: true, amount: 0.1, margin: "0px 0px -80px 0px" }}
                className={styles.projectItem}
              >
                <div className={styles.itemContent}>
                  <div className={styles.itemHeader}>
                    <h2 className={styles.projectTitle}>{project.title}</h2>
                    <a href={project.github} target="_blank" rel="noopener noreferrer" className={styles.githubBtn}>
                      [ GitHub ]
                    </a>
                  </div>
                  
                  <p className={styles.projectDesc}>{project.description}</p>
                  
                  <div className={styles.tagList}>
                    {project.tags.map((t) => (
                      <span key={t} className={styles.tag}>
                        #{t.toLowerCase().replace(/\s+/g, '')}
                      </span>
                    ))}
                  </div>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </section>
      </main>

      <Footer />
    </div>
  );
}