"use client";

import { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence, Variants } from 'framer-motion';
import Lenis from '@studio-freight/lenis';
import styles from './awards.module.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';

// Import data bersih dari JSON
import AWARDS_DATA from '@/json/awards.json';

interface AwardItem {
  id: number;
  title: string;
  institution: string;
  description: string;
  tags: string[];
  teamName: string; 
  leaderboard: string;
}

export default function AwardsPage() {
  const [activeTag, setActiveTag] = useState<string>("All");
  const [isOverflowing, setIsOverflowing] = useState<boolean>(false);
  
  const containerRef = useRef<HTMLDivElement>(null);
  const trackRef = useRef<HTMLDivElement>(null);

  // Arsitektur Physics Engine State (Virtual Rail Tracker)
  const pointerState = useRef({
    isDown: false,
    startX: 0,
    currentX: 0,
    lastX: 0,
    velocityX: 0,
    targetX: 0,
    singleSetWidth: 0,
  });

  const isDraggingRef = useRef<boolean>(false);

  // 1. Logic Smooth Scroll Lenis
  useEffect(() => {
    const lenis = new Lenis({
      duration: 1.2,
      easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
      smoothWheel: true,
    });

    function raf(time: number) {
      lenis.raf(time);
      requestAnimationFrame(raf);
    }

    requestAnimationFrame(raf);
    return () => lenis.destroy();
  }, []);

  // 2. Ambil & normalisasi data root JSON
  const awardsList = useMemo<AwardItem[]>(() => {
    return Array.isArray(AWARDS_DATA) ? AWARDS_DATA : AWARDS_DATA.awards;
  }, []);

  // 3. Filter Logic berdasarkan tag aktif
  const filteredAwards = useMemo<AwardItem[]>(() => {
    return activeTag === "All" 
      ? awardsList 
      : awardsList.filter((award) => award.tags.includes(activeTag));
  }, [activeTag, awardsList]);

  // 4. AUTO EXTRACT ALL TAGS
  const autoGeneratedTags = useMemo<string[]>(() => {
    const tagsSet = new Set<string>();
    awardsList.forEach((award) => {
      if (award.tags && Array.isArray(award.tags)) {
        award.tags.forEach((tag) => tagsSet.add(tag));
      }
    });
    return ["All", ...Array.from(tagsSet)];
  }, [awardsList]);

  // 5. Tripled Data untuk Infinite Loop Seamless Rail
  const renderedTags = useMemo(() => {
    return isOverflowing 
      ? [...autoGeneratedTags, ...autoGeneratedTags, ...autoGeneratedTags] 
      : autoGeneratedTags;
  }, [autoGeneratedTags, isOverflowing]);

  // 6. Deteksi Ukuran Riil & Set Posisi Awal Track Kereta
  useEffect(() => {
    const container = containerRef.current;
    const track = trackRef.current;
    if (!container || !track) return;

    const calculateSizes = () => {
      const containerWidth = container.clientWidth;
      const trackWidth = track.scrollWidth;

      if (!isOverflowing) {
        if (trackWidth > containerWidth) {
          setIsOverflowing(true);
        }
      } else {
        const singleSet = trackWidth / 3;
        pointerState.current.singleSetWidth = singleSet;
        
        if (singleSet <= containerWidth) {
          setIsOverflowing(false);
          pointerState.current.targetX = 0;
          track.style.transform = `translate3d(0px, 0px, 0px)`;
        } else {
          // Posisikan rel tepat di awal klaster ke-2 (tengah-tengah)
          pointerState.current.targetX = -singleSet;
        }
      }
    };

    const timeoutId = setTimeout(calculateSizes, 60);
    window.addEventListener('resize', calculateSizes);

    return () => {
      clearTimeout(timeoutId);
      window.removeEventListener('resize', calculateSizes);
    };
  }, [autoGeneratedTags, isOverflowing]);

  // 7. VIRTUAL PHYSICS MOMENTUM ENGINE (The Rail Loop System)
  useEffect(() => {
    const track = trackRef.current;
    if (!track || !isOverflowing) return;

    let animationFrameId: number;
    const state = pointerState.current;

    const updatePhysics = () => {
      // Pas lepas sentuhan, jalankan kalkulasi inersia gaya gesek peluruhan (Coefficient: 0.95)
      if (!state.isDown) {
        state.targetX += state.velocityX;
        state.velocityX *= 0.95; 
        
        if (Math.abs(state.velocityX) < 0.1) state.velocityX = 0;
      } else {
        // Akumulasi Delta X per frame untuk kalkulasi kecepatan luncur instan
        state.velocityX = state.currentX - state.lastX;
        state.lastX = state.currentX;
      }

      // SEAMLESS VIRTUAL SNAPPER (Reset Koordinat Tanpa Interupsi Gaya)
      const singleSet = state.singleSetWidth;
      
      // Kebabalasan ke Kiri (Menembus Klaster 3) -> Geser Halus ke Klaster 2
      if (state.targetX <= -(singleSet * 2)) {
        state.targetX += singleSet;
      }
      // Kebablasan ke Kanan (Menembus Klaster 1) -> Geser Halus ke Klaster 2
      else if (state.targetX >= 0) {
        state.targetX -= singleSet;
      }

      // Render posisi via GPU Matrix Matrix
      track.style.transform = `translate3d(${state.targetX}px, 0px, 0px)`;

      animationFrameId = requestAnimationFrame(updatePhysics);
    };

    animationFrameId = requestAnimationFrame(updatePhysics);
    return () => cancelAnimationFrame(animationFrameId);
  }, [isOverflowing, renderedTags]);

  // 8. UNIFIED GESTURE GATES (POINTER INTERACTION ARCHITECTURE)
  const pointerDown = (clientX: number) => {
    const state = pointerState.current;
    state.isDown = true;
    isDraggingRef.current = false;
    state.startX = clientX - state.targetX;
    state.currentX = clientX;
    state.lastX = clientX;
    state.velocityX = 0;
    
    if (trackRef.current) {
      trackRef.current.style.cursor = 'grabbing';
    }
  };

  const pointerMove = (clientX: number) => {
    const state = pointerState.current;
    if (!state.isDown) return;

    state.currentX = clientX;
    const newTargetX = clientX - state.startX;

    if (Math.abs(newTargetX - state.targetX) > 4) {
      isDraggingRef.current = true;
    }

    state.targetX = newTargetX;
  };

  const pointerUp = () => {
    const state = pointerState.current;
    state.isDown = false;
    
    if (trackRef.current) {
      trackRef.current.style.cursor = 'grab';
    }
    
    // Mikro-buffer timeout biar ga kepicu click event pasca nge-drag ekstrem
    setTimeout(() => {
      isDraggingRef.current = false;
    }, 20);
  };

  const handleTagClick = (tag: string) => {
    if (isDraggingRef.current) return;
    setActiveTag(activeTag === tag ? "All" : tag);
  };

  // FIX: Menggunakan interface Variants agar compiler TypeScript mengenali skema transisi motion secara legal
  const blockStackVariants: Variants = {
    hidden: { opacity: 0, x: 100, y: -50, rotateZ: 5, rotateY: -10, scale: 1.05 },
    visible: (customIndex: number) => ({ 
      opacity: 1, x: 0, y: 0, rotateZ: 0, rotateY: 0, scale: 1,
      transition: { type: "spring", stiffness: 85, damping: 14, mass: 0.8, delay: customIndex * 0.06 }
    }),
    discard: {
      opacity: 0, x: 200, y: 150, rotateZ: 10, rotateY: 5,
      transition: { duration: 0.45, ease: [0.36, 0, 0.66, -0.1] }
    }
  };

  return (
    <div className={styles.container}>
      <Navbar />

      <main className={styles.main}>
        {/* Hero Section */}
        <section className={styles.hero}>
          <motion.h1 
            className={styles.heroTitle}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }} 
          >
            AWARDS
          </motion.h1>
          <motion.p 
            className={styles.heroSub}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8 }}
          >
            Verifiable milestones, competitive performance logs, and academic recognitions.
          </motion.p>
        </section>

        {/* Outer Rail Constrains Viewport */}
        <div 
          ref={containerRef}
          className={`${styles.filterBarWrapper} ${isOverflowing ? styles.hasMask : ''}`}
          onTouchStart={(e) => pointerDown(e.touches[0].clientX)}
          onTouchMove={(e) => pointerMove(e.touches[0].clientX)}
          onTouchEnd={pointerUp}
          onMouseDown={(e) => pointerDown(e.clientX)}
          onMouseMove={(e) => { e.preventDefault(); pointerMove(e.clientX); }}
          onMouseUp={pointerUp}
          onMouseLeave={pointerUp}
        >
          <div 
            ref={trackRef}
            className={`${styles.filterBar} ${isOverflowing ? styles.canScroll : styles.isCentered}`}
          >
            {renderedTags.map((tag, index) => (
              <button 
                key={`${tag}-${index}`}
                onClick={() => handleTagClick(tag)}
                className={`${styles.filterBtn} ${activeTag === tag ? styles.active : ''}`}
              >
                {tag}
              </button>
            ))}
          </div>
        </div>

        {/* List Container */}
        <section className={styles.listContainer}>
          <AnimatePresence mode="popLayout">
            {filteredAwards.map((award, index) => (
              <motion.div 
                key={award.id}
                layout 
                custom={index} 
                variants={blockStackVariants}
                initial="hidden"
                whileInView="visible"
                exit="discard"
                viewport={{ once: true, amount: 0.1, margin: "0px 0px -100px 0px" }} 
                className={styles.awardItem}
              >
                <div className={styles.itemContent}>
                  <div className={styles.itemHeader}>
                    <div className={styles.titleBlock}>
                      <h2 className={styles.awardTitle}>{award.title}</h2>
                      <span className={styles.awardInstitution}>{award.institution}</span>
                    </div>
                    
                    {award.leaderboard && (
                      <div className={styles.actionWrapper}>
                        <a 
                          href={award.leaderboard} 
                          target="_blank" 
                          rel="noopener noreferrer" 
                          className={styles.leaderboardBtn}
                        >
                          {"[ VIEW RECORD ↗ ]"}
                        </a>
                      </div>
                    )}
                  </div>
                  
                  <p className={styles.awardDesc}>{award.description}</p>
                  
                  <div className={styles.tagList}>
                    {award.tags.map((t) => (
                      <span key={t} className={styles.tag}>
                        {`#${t.toLowerCase().replace(/\s+/g, '')}`}
                      </span>
                    ))}
                  </div>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </section>
      </main>

      <Footer />
    </div>
  );
}